/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.stockcontrolling;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.stockcontrolling.ControlProductDetails;
import lk.lztec.cbl.module.stockcontrolling.MNewProduct;
import lk.lztec.cbl.module.stockcontrolling.MProductDetails;
import lk.lztec.cbl.view.menu.StockControlling;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class AddToStock extends javax.swing.JFrame {

    /**
     * Creates new form AddToStock
     */
    public AddToStock() {
        initComponents();
        try {
            loaddata();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        QtyTextField = new javax.swing.JTextField();
        SaveNewProductButton = new javax.swing.JButton();
        ProductIdComboBox = new javax.swing.JComboBox();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        saveLabel = new javax.swing.JLabel();
        TableButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add To Stock");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(36, 31, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Products_Id");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 40));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Qty");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 30));

        QtyTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        QtyTextField.setForeground(new java.awt.Color(204, 204, 204));
        QtyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        QtyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        QtyTextField.setOpaque(false);
        jPanel3.add(QtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 310, -1));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/input_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Enter");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 31, 60)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 120, 30));

        ProductIdComboBox.setBackground(new java.awt.Color(0, 153, 153));
        ProductIdComboBox.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        ProductIdComboBox.setForeground(new java.awt.Color(255, 255, 255));
        ProductIdComboBox.setOpaque(false);
        ProductIdComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductIdComboBoxMouseClicked(evt);
            }
        });
        jPanel3.add(ProductIdComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 310, 30));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        saveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        saveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(saveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        TableButton1.setBackground(new java.awt.Color(127, 90, 240));
        TableButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableButton1.setForeground(new java.awt.Color(204, 204, 204));
        TableButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/data_sheet_20px.png"))); // NOI18N
        TableButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        TableButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableButton1.setOpaque(false);
        TableButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(TableButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 120, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        LsTable.setBackground(new java.awt.Color(0, 153, 153));
        LsTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LsTable.setForeground(new java.awt.Color(204, 204, 204));
        LsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Product Id", "qty", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LsTable.setGridColor(new java.awt.Color(255, 255, 255));
        LsTable.setOpaque(false);
        LsTable.setSelectionBackground(new java.awt.Color(153, 255, 204));
        LsTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(LsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 390, 620));

        setSize(new java.awt.Dimension(833, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String pid = ProductIdComboBox.getSelectedItem().toString();
        int qty = Integer.parseInt(QtyTextField.getText());

        boolean isAdded;
        try {
            isAdded = ControlProductDetails.enterNewItem(pid, qty);
            boolean isUpdate = ControlProductDetails.updateqty(pid, qty);
            if (isAdded) {
                QtyTextField.setText("");
                saveLabel.setText("Saved");
                TableButton1.doClick();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new StockControlling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    private void TableButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) LsTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MNewProduct> list = null;
       
        try {
            list = new ControlProductDetails().getAllstockadd();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getProductid();
            row[2] = list.get(i).getQty();
            row[3] = list.get(i).getData();
            model.addRow(row);
        }
    }//GEN-LAST:event_TableButton1ActionPerformed

    private void ProductIdComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductIdComboBoxMouseClicked
        String pid = ProductIdComboBox.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) LsTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MNewProduct> list = null;

        try {
            list = new ControlProductDetails().loadnewp(pid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToStock.class.getName()).log(Level.SEVERE, null, ex);
        }

        Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getProductid();
            row[2] = list.get(i).getQty();
            row[3] = list.get(i).getData();
            model.addRow(row);
        }
          
    }//GEN-LAST:event_ProductIdComboBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddToStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton1;
    private javax.swing.JButton LockButton1;
    private javax.swing.JTable LsTable;
    private javax.swing.JComboBox ProductIdComboBox;
    private javax.swing.JTextField QtyTextField;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JButton TableButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel saveLabel;
    // End of variables declaration//GEN-END:variables

    private void loaddata() throws ClassNotFoundException, SQLException {
        for (MProductDetails temp : new ControlProductDetails().getAllItem()) {
            ProductIdComboBox.addItem(temp.getPid());
        }
    }
}
