/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.stockcontrolling;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.stockcontrolling.ControlLorryStock;
import lk.lztec.cbl.control.stockcontrolling.ControlProductDetails;
import lk.lztec.cbl.module.stockcontrolling.MLorryStock;
import lk.lztec.cbl.module.stockcontrolling.MProductDetails;
import lk.lztec.cbl.module.stockcontrolling.MstocklorryIn;
import lk.lztec.cbl.view.employeemanagement.DriverAttendence;
import lk.lztec.cbl.view.menu.StockControlling;
import lk.lztec.cbl.view.security.LogScreen;
import lk.lztec.cbl.view.transport.Newlorry;

/**
 *
 * @author Ishan
 */
public class AddToLorry extends javax.swing.JFrame {

    /**
     * Creates new form AddToLorry
     */
    public AddToLorry() {
        initComponents();
        try {
            lorryStock();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToLorry.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToLorry.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        QtyTextField = new javax.swing.JTextField();
        SaveNewProductButton = new javax.swing.JButton();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        SaveLabel = new javax.swing.JLabel();
        LorryStockIdComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        LsTable = new javax.swing.JTable();
        TableButton = new javax.swing.JButton();
        pidLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add To Lorry");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(36, 31, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Lorry_Stock_Id");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 40));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Qty");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 30));

        QtyTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        QtyTextField.setForeground(new java.awt.Color(204, 204, 204));
        QtyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        QtyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        QtyTextField.setOpaque(false);
        jPanel3.add(QtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 310, -1));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/input_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Enter");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 31, 60)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 120, 30));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        SaveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SaveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(SaveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        LorryStockIdComboBox.setBackground(new java.awt.Color(0, 153, 153));
        LorryStockIdComboBox.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        LorryStockIdComboBox.setForeground(new java.awt.Color(255, 255, 255));
        LorryStockIdComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                LorryStockIdComboBoxItemStateChanged(evt);
            }
        });
        LorryStockIdComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LorryStockIdComboBoxMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LorryStockIdComboBoxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LorryStockIdComboBoxMouseReleased(evt);
            }
        });
        LorryStockIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LorryStockIdComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(LorryStockIdComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 310, -1));

        LsTable.setBackground(new java.awt.Color(0, 153, 153));
        LsTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        LsTable.setForeground(new java.awt.Color(204, 204, 204));
        LsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Lorry Stock Id", "qty", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LsTable.setGridColor(new java.awt.Color(255, 255, 255));
        LsTable.setOpaque(false);
        LsTable.setSelectionBackground(new java.awt.Color(153, 255, 204));
        LsTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(LsTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 390, 620));

        TableButton.setBackground(new java.awt.Color(127, 90, 240));
        TableButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableButton.setForeground(new java.awt.Color(204, 204, 204));
        TableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/data_sheet_20px.png"))); // NOI18N
        TableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        TableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableButton.setOpaque(false);
        TableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButtonActionPerformed(evt);
            }
        });
        jPanel3.add(TableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 120, 50));

        pidLabel.setBackground(new java.awt.Color(204, 204, 255));
        pidLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        pidLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(pidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 320, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 620));

        setSize(new java.awt.Dimension(836, 652));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new StockControlling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String lsid = LorryStockIdComboBox.getSelectedItem().toString();
        int qty = Integer.parseInt(QtyTextField.getText());

        try {
            boolean isAdd = ControlLorryStock.addItem(lsid, qty);
            boolean isUpdate = ControlLorryStock.updateqty(lsid, qty);
            boolean isUpdatep = ControlProductDetails.downqty(ControlLorryStock.getPid((String) LorryStockIdComboBox.getSelectedItem()), qty);
            if (isAdd) {
                SaveLabel.setText("Saved");
                TableButton.doClick();
           }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    private void TableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) LsTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MstocklorryIn> list = null;
        try {
            list = new ControlLorryStock().loadstockTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getLsid();
            row[2] = list.get(i).getQty();
            row[3] = list.get(i).getDate();
            model.addRow(row);
        }
    }//GEN-LAST:event_TableButtonActionPerformed

    private void LorryStockIdComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_LorryStockIdComboBoxItemStateChanged

    }//GEN-LAST:event_LorryStockIdComboBoxItemStateChanged

    private void LorryStockIdComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LorryStockIdComboBoxMouseClicked
        String lsid = LorryStockIdComboBox.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) LsTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MstocklorryIn> list = null;

      
        try {
            list = new ControlLorryStock().loadnewls(lsid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToLorry.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToLorry.class.getName()).log(Level.SEVERE, null, ex);
        }
       

       Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getLsid();
            row[2] = list.get(i).getQty();
            row[3] = list.get(i).getDate();
            model.addRow(row);
        }
    }//GEN-LAST:event_LorryStockIdComboBoxMouseClicked

    private void LorryStockIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LorryStockIdComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LorryStockIdComboBoxActionPerformed

    private void LorryStockIdComboBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LorryStockIdComboBoxMousePressed
        DefaultTableModel model = (DefaultTableModel) LsTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MstocklorryIn> list = null;
        try {
            list = new ControlLorryStock().loadstockTable();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getLsid();
            row[2] = list.get(i).getQty();
            row[3] = list.get(i).getDate();
            model.addRow(row);
        }

    }//GEN-LAST:event_LorryStockIdComboBoxMousePressed

    private void LorryStockIdComboBoxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LorryStockIdComboBoxMouseReleased

    }//GEN-LAST:event_LorryStockIdComboBoxMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToLorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToLorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToLorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToLorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddToLorry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton1;
    private javax.swing.JButton LockButton1;
    private javax.swing.JComboBox LorryStockIdComboBox;
    private javax.swing.JTable LsTable;
    private javax.swing.JTextField QtyTextField;
    private javax.swing.JLabel SaveLabel;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JButton TableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pidLabel;
    // End of variables declaration//GEN-END:variables

    private void lorryStock() throws ClassNotFoundException, SQLException {
        for (MLorryStock temp : new ControlLorryStock().loadlsTable()) {
            LorryStockIdComboBox.addItem(temp.getLsid());
        }
    }

}
