/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.stockcontrolling;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.stockcontrolling.ControlProductDetails;
import lk.lztec.cbl.module.stockcontrolling.MProductDetails;
import lk.lztec.cbl.view.menu.StockControlling;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class LIveStock extends javax.swing.JFrame {

    /**
     * Creates new form LIveStock
     */
    public LIveStock() {
         try {
            initComponents();
            loadAllItems();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(LIveStock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        LockButton1 = new javax.swing.JButton();
        DoneButton1 = new javax.swing.JButton();
        qtyButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Live Stock");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(36, 31, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        ProductTable.setBackground(new java.awt.Color(0, 153, 153));
        ProductTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        ProductTable.setForeground(new java.awt.Color(255, 255, 255));
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Products Id", "Product Name", "Weight", "Packets", "Qty", "Buying Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProductTable.setGridColor(new java.awt.Color(255, 255, 255));
        ProductTable.setOpaque(false);
        ProductTable.setSelectionBackground(new java.awt.Color(51, 255, 204));
        ProductTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(ProductTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 560));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 360, 60));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 330, 60));

        qtyButton2.setBackground(new java.awt.Color(85, 91, 111));
        qtyButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        qtyButton2.setForeground(new java.awt.Color(204, 204, 204));
        qtyButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/stocks_20px.png"))); // NOI18N
        qtyButton2.setText("Low-Hight ");
        qtyButton2.setBorder(null);
        qtyButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qtyButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(qtyButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 140, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        setSize(new java.awt.Dimension(849, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new StockControlling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void qtyButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
         int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MProductDetails> list = null;
        try {
            list = new ControlProductDetails().loadProductTableq();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LIveStock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LIveStock.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object row[]=new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0]=list.get(i).getPid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getWeight();
            row[3]=list.get(i).getPackets();
            row[4]=list.get(i).getQty();
            row[5]=list.get(i).getBprice();
            model.addRow(row);
        }
    }//GEN-LAST:event_qtyButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIveStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIveStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LIveStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LIveStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LIveStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton1;
    private javax.swing.JButton LockButton1;
    private javax.swing.JTable ProductTable;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton qtyButton2;
    // End of variables declaration//GEN-END:variables

    private void loadAllItems() throws ClassNotFoundException, SQLException {
        
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        
        List<MProductDetails> list= new ControlProductDetails().loadProductTable();
        Object row[]=new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0]=list.get(i).getPid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getWeight();
            row[3]=list.get(i).getPackets();
            row[4]=list.get(i).getQty();
            row[5]=list.get(i).getBprice();
            model.addRow(row);
        }
    }
}
