/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.stockcontrolling;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.lztec.cbl.control.stockcontrolling.ControlLorryStock;
import lk.lztec.cbl.control.stockcontrolling.ControlProductDetails;
import lk.lztec.cbl.control.transport.Controllorry;
import lk.lztec.cbl.module.stockcontrolling.MLorryStock;
import lk.lztec.cbl.module.stockcontrolling.MProductDetails;
import lk.lztec.cbl.module.transport.MNewlorry;
import lk.lztec.cbl.view.menu.StockControlling;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class LorryStockSetting extends javax.swing.JFrame {

    private MLorryStock MLorryStock;

    /**
     * Creates new form LorryStockSetting
     */
    public LorryStockSetting() {
        initComponents();
        try {
            getAlllorry();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LorryStockSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LorryStockSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            loadpid();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LorryStockSetting.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LorryStockSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        UpdateBuyingPriceButton = new javax.swing.JButton();
        SaveNewProductButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SellingPriceTextField = new javax.swing.JTextField();
        IdTextField = new javax.swing.JTextField();
        QtyTextField = new javax.swing.JTextField();
        DeleteButton1 = new javax.swing.JButton();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        SaveLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PidComboBox1 = new javax.swing.JComboBox();
        LidComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lorry Stock Setting");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        UpdateBuyingPriceButton.setBackground(new java.awt.Color(127, 90, 240));
        UpdateBuyingPriceButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UpdateBuyingPriceButton.setForeground(new java.awt.Color(36, 31, 60));
        UpdateBuyingPriceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/update_20px.png"))); // NOI18N
        UpdateBuyingPriceButton.setBorder(null);
        UpdateBuyingPriceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateBuyingPriceButton.setOpaque(false);
        UpdateBuyingPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyingPriceButtonActionPerformed(evt);
            }
        });
        jPanel3.add(UpdateBuyingPriceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 50, 30));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/save_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Save");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 120, 30));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Id");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 40));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Lorry_Number");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Product_id");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Selling_Price");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 30));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Qty");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 30));

        SellingPriceTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SellingPriceTextField.setForeground(new java.awt.Color(204, 204, 204));
        SellingPriceTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        SellingPriceTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SellingPriceTextField.setOpaque(false);
        jPanel3.add(SellingPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 310, -1));

        IdTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        IdTextField.setForeground(new java.awt.Color(204, 204, 204));
        IdTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        IdTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IdTextField.setOpaque(false);
        jPanel3.add(IdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 310, -1));

        QtyTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        QtyTextField.setForeground(new java.awt.Color(204, 204, 204));
        QtyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        QtyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        QtyTextField.setOpaque(false);
        jPanel3.add(QtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 310, -1));

        DeleteButton1.setBackground(new java.awt.Color(127, 90, 240));
        DeleteButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DeleteButton1.setForeground(new java.awt.Color(204, 204, 204));
        DeleteButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/trash_20px.png"))); // NOI18N
        DeleteButton1.setText("Delete");
        DeleteButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        DeleteButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton1.setOpaque(false);
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DeleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 120, 30));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        SaveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SaveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(SaveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 170, 50));

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 0, 89));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 160, 50));

        PidComboBox1.setBackground(new java.awt.Color(0, 153, 153));
        PidComboBox1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        PidComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        PidComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel3.add(PidComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 310, -1));

        LidComboBox2.setBackground(new java.awt.Color(0, 153, 153));
        LidComboBox2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        LidComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        LidComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel3.add(LidComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        setSize(new java.awt.Dimension(447, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBuyingPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyingPriceButtonActionPerformed
        String id = IdTextField.getText();
        double bprice = Double.parseDouble(SellingPriceTextField.getText());
        try {

            boolean isUpdated = ControlLorryStock.updatesprice(id, bprice);
            if (isUpdated) {
                SaveLabel.setText("Update Success");

            } else {
                SaveLabel.setText("Update fail..");
            }

        } catch (SQLException | ClassNotFoundException ex) {

        }


    }//GEN-LAST:event_UpdateBuyingPriceButtonActionPerformed

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String lsid = IdTextField.getText();
        String lnplate = LidComboBox2.getSelectedItem().toString();
        String pid = PidComboBox1.getSelectedItem().toString();
        double sprice = Double.parseDouble(SellingPriceTextField.getText());
        int qty = Integer.parseInt(QtyTextField.getText());
        

        try {
            boolean isAdded = ControlLorryStock.saveItem(lsid, lnplate, pid, sprice, qty);
              boolean isUpdatep = ControlProductDetails.downqty(pid,qty);
            if (isAdded) {
                SaveLabel.setText("save");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed

    }//GEN-LAST:event_DeleteButton1ActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new StockControlling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LorryStockSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LorryStockSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LorryStockSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LorryStockSetting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LorryStockSetting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JButton DoneButton1;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JComboBox LidComboBox2;
    private javax.swing.JButton LockButton1;
    private javax.swing.JComboBox PidComboBox1;
    private javax.swing.JTextField QtyTextField;
    private javax.swing.JLabel SaveLabel;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JTextField SellingPriceTextField;
    private javax.swing.JButton UpdateBuyingPriceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void loadpid() throws ClassNotFoundException, SQLException {
        for (MProductDetails temp : new ControlProductDetails().getAllItem()) {
            PidComboBox1.addItem(temp.getPid());
        }

    }

    private void getAlllorry() throws ClassNotFoundException, SQLException {
        for (MNewlorry temp : new Controllorry().getAllLorry()) {
            LidComboBox2.addItem(temp.getNplate());
        }
    }
}
