/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.stockcontrolling;

import lk.lztec.cbl.view.menu.StockControlling;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.stockcontrolling.ControlProductDetails;
import lk.lztec.cbl.module.stockcontrolling.MProductDetails;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class ProductDetails extends javax.swing.JFrame {

    /**
     * Creates new form ProductDetails
     */
    public ProductDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        UpdateBuyingPriceButton = new javax.swing.JButton();
        SaveNewProductButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BuyingPriceTextField = new javax.swing.JTextField();
        IdTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        WeightTextField = new javax.swing.JTextField();
        PacketsCountTextField = new javax.swing.JTextField();
        QtyTextField = new javax.swing.JTextField();
        DeleteButton1 = new javax.swing.JButton();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        SaveLabel = new javax.swing.JLabel();
        DeleteLabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProductDetails");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        UpdateBuyingPriceButton.setBackground(new java.awt.Color(127, 90, 240));
        UpdateBuyingPriceButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UpdateBuyingPriceButton.setForeground(new java.awt.Color(36, 31, 60));
        UpdateBuyingPriceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/update_20px.png"))); // NOI18N
        UpdateBuyingPriceButton.setBorder(null);
        UpdateBuyingPriceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateBuyingPriceButton.setOpaque(false);
        UpdateBuyingPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyingPriceButtonActionPerformed(evt);
            }
        });
        jPanel3.add(UpdateBuyingPriceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 50, 30));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/save_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Save");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 120, 30));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Id");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 40));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Weight");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 30));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Packets Count");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 30));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Buying Price");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 30));

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Qty");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        BuyingPriceTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        BuyingPriceTextField.setForeground(new java.awt.Color(204, 204, 204));
        BuyingPriceTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        BuyingPriceTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BuyingPriceTextField.setOpaque(false);
        jPanel3.add(BuyingPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 310, -1));

        IdTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        IdTextField.setForeground(new java.awt.Color(204, 204, 204));
        IdTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        IdTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IdTextField.setOpaque(false);
        jPanel3.add(IdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 310, -1));

        NameTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        NameTextField.setForeground(new java.awt.Color(204, 204, 204));
        NameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        NameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NameTextField.setOpaque(false);
        jPanel3.add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 310, -1));

        WeightTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        WeightTextField.setForeground(new java.awt.Color(204, 204, 204));
        WeightTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        WeightTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        WeightTextField.setOpaque(false);
        jPanel3.add(WeightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 310, -1));

        PacketsCountTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        PacketsCountTextField.setForeground(new java.awt.Color(204, 204, 204));
        PacketsCountTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        PacketsCountTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PacketsCountTextField.setOpaque(false);
        jPanel3.add(PacketsCountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 310, -1));

        QtyTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        QtyTextField.setForeground(new java.awt.Color(204, 204, 204));
        QtyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        QtyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        QtyTextField.setOpaque(false);
        jPanel3.add(QtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 310, -1));

        DeleteButton1.setBackground(new java.awt.Color(127, 90, 240));
        DeleteButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DeleteButton1.setForeground(new java.awt.Color(204, 204, 204));
        DeleteButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/trash_20px.png"))); // NOI18N
        DeleteButton1.setText("Delete");
        DeleteButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        DeleteButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton1.setOpaque(false);
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DeleteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 120, 30));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        SaveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SaveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(SaveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 170, 50));

        DeleteLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        DeleteLabel.setForeground(new java.awt.Color(250, 0, 89));
        jPanel3.add(DeleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 160, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        setSize(new java.awt.Dimension(444, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBuyingPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyingPriceButtonActionPerformed
        String id = IdTextField.getText();
        double bprice = Double.parseDouble(BuyingPriceTextField.getText());
       
        try {

            boolean isUpdated = ControlProductDetails.updateBprice(id, bprice);
            if (isUpdated) {
                SaveLabel.setText("Update Success");

            } else {
                SaveLabel.setText("Update fail..");
            }

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_UpdateBuyingPriceButtonActionPerformed

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String id = IdTextField.getText();
        String name = NameTextField.getText();
        int weight = Integer.parseInt(WeightTextField.getText());
        int packets = Integer.parseInt(PacketsCountTextField.getText());
        int qty = Integer.parseInt(QtyTextField.getText());
        double bprice = Double.parseDouble(BuyingPriceTextField.getText());
        MProductDetails mProductDetails = new MProductDetails(id, name, weight, packets,qty , bprice);
        try {
            boolean isAdded = ControlProductDetails.saveItem(mProductDetails);
            if (isAdded) {
                IdTextField.setText("");
                NameTextField.setText("");
                WeightTextField.setText("");
                PacketsCountTextField.setText("");
                QtyTextField.setText("");
                BuyingPriceTextField.setText("");
                SaveLabel.setText("Saved");
                DeleteLabel.setText("");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed
        String id = IdTextField.getText();
        try {
            boolean isDeleted = ControlProductDetails.DeleteItem(id);
            if (isDeleted) {
                SaveLabel.setText("");
                DeleteLabel.setText("Deleted..");
            } else {

                SaveLabel.setText("");
                DeleteLabel.setText("Deleted fail..");
            }

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_DeleteButton1ActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new StockControlling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuyingPriceTextField;
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JLabel DeleteLabel;
    private javax.swing.JButton DoneButton1;
    private javax.swing.JTextField IdTextField;
    private javax.swing.JButton LockButton1;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PacketsCountTextField;
    private javax.swing.JTextField QtyTextField;
    private javax.swing.JLabel SaveLabel;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JButton UpdateBuyingPriceButton;
    private javax.swing.JTextField WeightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
