/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.transport;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.lztec.cbl.control.employeemanagement.ControlDriverDetails;
import lk.lztec.cbl.control.employeemanagement.ControlHelperDetails;
import lk.lztec.cbl.control.transport.Controllorry;
import lk.lztec.cbl.module.employeemanagement.MDriverDetails;
import lk.lztec.cbl.module.employeemanagement.MHelperDetails;
import lk.lztec.cbl.view.security.LogScreen;
import lk.lztec.cbl.view.menu.Transport;

/**
 *
 * @author Ishan
 */
public class Newlorry extends javax.swing.JFrame {

    /**
     * Creates new form Newlorry
     */
    public Newlorry() {
       initComponents();
        try {
            
            loadDrivers();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Newlorry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        SaveNewProductButton = new javax.swing.JButton();
        LorryNumberPlateTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        saveLabel = new javax.swing.JLabel();
        DeleteLabel = new javax.swing.JLabel();
        DriverNicComboBox = new javax.swing.JComboBox();
        HelperNicComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Lorry");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Driver_Nic");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 40));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Helper_Nic");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        DeleteButton.setBackground(new java.awt.Color(127, 90, 240));
        DeleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(204, 204, 204));
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/trash_20px.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.setOpaque(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel3.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 120, 30));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/save_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Save");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 120, 30));

        LorryNumberPlateTextField1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        LorryNumberPlateTextField1.setForeground(new java.awt.Color(204, 204, 204));
        LorryNumberPlateTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        LorryNumberPlateTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LorryNumberPlateTextField1.setOpaque(false);
        jPanel3.add(LorryNumberPlateTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 310, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Lorry_Number_Plate");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 40));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        saveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        saveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(saveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        DeleteLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        DeleteLabel.setForeground(new java.awt.Color(250, 0, 89));
        jPanel3.add(DeleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        DriverNicComboBox.setBackground(new java.awt.Color(0, 153, 153));
        DriverNicComboBox.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        DriverNicComboBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(DriverNicComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 310, 30));

        HelperNicComboBox.setBackground(new java.awt.Color(0, 153, 153));
        HelperNicComboBox.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        HelperNicComboBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(HelperNicComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 310, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        setSize(new java.awt.Dimension(443, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String nplate = LorryNumberPlateTextField1.getText();
        try {
            boolean isDeleted = Controllorry.Deletelorry(nplate);
            if (isDeleted) {
                DeleteLabel.setText("Deleted ");
                saveLabel.setText("");
            } else {
                DeleteLabel.setText("Delete fail");
                saveLabel.setText("");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String nplate = LorryNumberPlateTextField1.getText();
        String dnic =DriverNicComboBox.getSelectedItem().toString();
        String hnic = HelperNicComboBox.getSelectedItem().toString();
        try {
            boolean isAdded = Controllorry.saveLorry(nplate, dnic, hnic);
            if (isAdded) {
                LorryNumberPlateTextField1.setText("");
                saveLabel.setText("Saved");
                DeleteLabel.setText("");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new Transport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newlorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newlorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newlorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newlorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newlorry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DeleteLabel;
    private javax.swing.JButton DoneButton1;
    private javax.swing.JComboBox DriverNicComboBox;
    private javax.swing.JComboBox HelperNicComboBox;
    private javax.swing.JButton LockButton1;
    private javax.swing.JTextField LorryNumberPlateTextField1;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel saveLabel;
    // End of variables declaration//GEN-END:variables

    private void loadDrivers() throws ClassNotFoundException, SQLException {
        for(MDriverDetails temp: new ControlDriverDetails().getAllDrivers()){
            DriverNicComboBox.addItem(temp.getNic());
        }
      for(MHelperDetails temp: new ControlHelperDetails().getAllHelpers()){
        HelperNicComboBox.addItem(temp.getNic());
       }
    }
}
