/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.financemanagement;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.financemanagement.Controlfingmang;
import lk.lztec.cbl.module.financemanagement.MfinMang;
import lk.lztec.cbl.view.menu.FinanceManagement;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class Rent extends javax.swing.JFrame {

    /**
     * Creates new form Rent
     */
    public Rent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rentTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DescriptionTextField = new javax.swing.JTextField();
        AmountTextField = new javax.swing.JTextField();
        TableButton = new javax.swing.JButton();
        SaveLabel = new javax.swing.JLabel();
        LockButton1 = new javax.swing.JButton();
        DoneButton1 = new javax.swing.JButton();
        SaveNewProductButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rent");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        rentTable.setBackground(new java.awt.Color(0, 153, 153));
        rentTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        rentTable.setForeground(new java.awt.Color(255, 255, 255));
        rentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "date", "description", "amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rentTable.setGridColor(new java.awt.Color(255, 255, 255));
        rentTable.setOpaque(false);
        rentTable.setSelectionBackground(new java.awt.Color(153, 255, 204));
        rentTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(rentTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 400, 620));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Description");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 40));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Amount");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 30));

        DescriptionTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        DescriptionTextField.setForeground(new java.awt.Color(204, 204, 204));
        DescriptionTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        DescriptionTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DescriptionTextField.setOpaque(false);
        jPanel3.add(DescriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 310, -1));

        AmountTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        AmountTextField.setForeground(new java.awt.Color(204, 204, 204));
        AmountTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        AmountTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AmountTextField.setOpaque(false);
        jPanel3.add(AmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 310, -1));

        TableButton.setBackground(new java.awt.Color(127, 90, 240));
        TableButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableButton.setForeground(new java.awt.Color(204, 204, 204));
        TableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/data_sheet_20px.png"))); // NOI18N
        TableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        TableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableButton.setOpaque(false);
        TableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButtonActionPerformed(evt);
            }
        });
        jPanel3.add(TableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 120, 50));

        SaveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SaveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(SaveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/save_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Save");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 120, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 620));

        setSize(new java.awt.Dimension(848, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButtonActionPerformed
       DefaultTableModel model = (DefaultTableModel) rentTable.getModel();
       int a=model.getRowCount();
            for(int i=0;i<a;i++){   
                model.removeRow(0);
            }
        List<MfinMang> list = null;
        try {
            list = new Controlfingmang().loadrent();
        } catch (SQLException ex) {
            Logger.getLogger(Rent.class.getName()).log(Level.SEVERE, null, ex);
        }

        for(MfinMang detail:list){
        model.addRow(new Object[]{detail.getNo(),detail.getDate(),detail.getDes(),detail.getAmount()});
        }
    }//GEN-LAST:event_TableButtonActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new FinanceManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String des=DescriptionTextField.getText();
        double amount=Double.parseDouble(AmountTextField.getText());
        try {
            boolean isAdded = Controlfingmang.saveRent(des, amount);
            TableButton.doClick();
            if (isAdded) {
                DescriptionTextField.setText("");
                AmountTextField.setText("");
                SaveLabel.setText("Saved");

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountTextField;
    private javax.swing.JTextField DescriptionTextField;
    private javax.swing.JButton DoneButton1;
    private javax.swing.JButton LockButton1;
    private javax.swing.JLabel SaveLabel;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JButton TableButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rentTable;
    // End of variables declaration//GEN-END:variables
}
