/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.employeemanagement;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.employeemanagement.ControlDriverDetails;
import lk.lztec.cbl.module.employeemanagement.MDriverAt;
import lk.lztec.cbl.module.employeemanagement.MDriverDetails;
import lk.lztec.cbl.module.employeemanagement.MDriverSa;
import lk.lztec.cbl.view.menu.EmployeeManagement;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class DriverSalary extends javax.swing.JFrame {

    /**
     * Creates new form DriverSalary
     */
    public DriverSalary() {
        initComponents();
        try {
            Drivernic();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AmountTextField3 = new javax.swing.JTextField();
        TableButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DriverSalaryTable = new javax.swing.JTable();
        DriverNicComboBox = new javax.swing.JComboBox();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        saveLabel = new javax.swing.JLabel();
        PaidButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Driver Salary");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(24, 23, 54));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setForeground(new java.awt.Color(36, 31, 60));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Driver_Nic");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 40));

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Amount ");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        AmountTextField3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        AmountTextField3.setForeground(new java.awt.Color(204, 204, 204));
        AmountTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        AmountTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AmountTextField3.setOpaque(false);
        jPanel6.add(AmountTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 310, -1));

        TableButton.setBackground(new java.awt.Color(127, 90, 240));
        TableButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableButton.setForeground(new java.awt.Color(204, 204, 204));
        TableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/data_sheet_20px.png"))); // NOI18N
        TableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        TableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableButton.setOpaque(false);
        TableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButtonActionPerformed(evt);
            }
        });
        jPanel6.add(TableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 120, 50));

        DriverSalaryTable.setBackground(new java.awt.Color(0, 153, 153));
        DriverSalaryTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        DriverSalaryTable.setForeground(new java.awt.Color(204, 204, 204));
        DriverSalaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Driver_Nic", "Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DriverSalaryTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DriverSalaryTable.setGridColor(new java.awt.Color(255, 255, 255));
        DriverSalaryTable.setOpaque(false);
        DriverSalaryTable.setSelectionBackground(new java.awt.Color(153, 255, 204));
        DriverSalaryTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(DriverSalaryTable);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 460, 620));

        DriverNicComboBox.setBackground(new java.awt.Color(0, 153, 153));
        DriverNicComboBox.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        DriverNicComboBox.setForeground(new java.awt.Color(255, 255, 255));
        DriverNicComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        DriverNicComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DriverNicComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DriverNicComboBoxMouseClicked(evt);
            }
        });
        jPanel6.add(DriverNicComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 310, 30));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 210, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        saveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        saveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel6.add(saveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        PaidButton1.setBackground(new java.awt.Color(127, 90, 240));
        PaidButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PaidButton1.setForeground(new java.awt.Color(204, 204, 204));
        PaidButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/low_price_20px.png"))); // NOI18N
        PaidButton1.setText("Paid");
        PaidButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        PaidButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PaidButton1.setOpaque(false);
        PaidButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(PaidButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 620));

        setSize(new java.awt.Dimension(895, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) DriverSalaryTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MDriverSa> list = null;
        try {
            list = new ControlDriverDetails().loadDriverSa();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getDnic();
            row[2] = list.get(i).getSal();
            row[3] = list.get(i).getDate();
            model.addRow(row);
        }
    }//GEN-LAST:event_TableButtonActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new EmployeeManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    private void PaidButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidButton1ActionPerformed
        String id = DriverNicComboBox.getSelectedItem().toString();
        int sal = Integer.parseInt(AmountTextField3.getText());
        try {
            boolean isAdded = ControlDriverDetails.saveDriverSa(id, sal);
            if (isAdded) {
                saveLabel.setText("Saved");
                DefaultTableModel model = (DefaultTableModel) DriverSalaryTable.getModel();
                int a = model.getRowCount();
                for (int i = 0; i < a; i++) {
                    model.removeRow(0);
                }
                List<MDriverSa> list = null;
                try {
                    list = new ControlDriverDetails().loadDriverSa();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DriverSalary.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DriverSalary.class.getName()).log(Level.SEVERE, null, ex);
                }
                Object row[] = new Object[4];
                for (int i = 0; i < list.size(); i++) {
                    row[0] = list.get(i).getNo();
                    row[1] = list.get(i).getDnic();
                    row[2] = list.get(i).getSal();
                    row[3] = list.get(i).getDate();
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_PaidButton1ActionPerformed

    private void DriverNicComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DriverNicComboBoxMouseClicked
          String nic = DriverNicComboBox.getSelectedItem().toString();
         
        DefaultTableModel model = (DefaultTableModel) DriverSalaryTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MDriverSa> list = null;

        try {
            list = new ControlDriverDetails().loadDriSa(nic);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }

        Object row[] = new Object[4];
                for (int i = 0; i < list.size(); i++) {
                    row[0] = list.get(i).getNo();
                    row[1] = list.get(i).getDnic();
                    row[2] = list.get(i).getSal();
                    row[3] = list.get(i).getDate();
                    model.addRow(row);
                }
    }//GEN-LAST:event_DriverNicComboBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountTextField3;
    private javax.swing.JButton DoneButton1;
    private javax.swing.JComboBox DriverNicComboBox;
    private javax.swing.JTable DriverSalaryTable;
    private javax.swing.JButton LockButton1;
    private javax.swing.JButton PaidButton1;
    private javax.swing.JButton TableButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel saveLabel;
    // End of variables declaration//GEN-END:variables

    private void Drivernic() throws ClassNotFoundException, SQLException {
        for (MDriverDetails temp : new ControlDriverDetails().getAllDrivers()) {
            DriverNicComboBox.addItem(temp.getNic());
        }
    }

}
