/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.employeemanagement;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.employeemanagement.ControlDriverDetails;

import lk.lztec.cbl.module.employeemanagement.MDriverAt;
import lk.lztec.cbl.module.employeemanagement.MDriverDetails;
import lk.lztec.cbl.view.menu.EmployeeManagement;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class DriverAttendence extends javax.swing.JFrame {

    /**
     * Creates new form DriverDetail
     */
    public DriverAttendence() {
        initComponents();
        try {
            Drivernic();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * b WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DriverTable = new javax.swing.JTable();
        WorkingButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        DriverNicComboBox = new javax.swing.JComboBox();
        saveLabel = new javax.swing.JLabel();
        TableButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DriverAttendence");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(36, 31, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        DriverTable.setBackground(new java.awt.Color(0, 153, 153));
        DriverTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        DriverTable.setForeground(new java.awt.Color(204, 204, 204));
        DriverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Driver_Nic", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DriverTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DriverTable.setGridColor(new java.awt.Color(255, 255, 255));
        DriverTable.setOpaque(false);
        DriverTable.setSelectionBackground(new java.awt.Color(153, 255, 204));
        DriverTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(DriverTable);
        if (DriverTable.getColumnModel().getColumnCount() > 0) {
            DriverTable.getColumnModel().getColumn(0).setResizable(false);
            DriverTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 390, 620));

        WorkingButton.setBackground(new java.awt.Color(0, 153, 153));
        WorkingButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        WorkingButton.setForeground(new java.awt.Color(204, 204, 204));
        WorkingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/driver_20px.png"))); // NOI18N
        WorkingButton.setText("Working");
        WorkingButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        WorkingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        WorkingButton.setOpaque(false);
        WorkingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkingButtonActionPerformed(evt);
            }
        });
        jPanel3.add(WorkingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 120, 30));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Driver_Nic");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 40));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 210, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        DriverNicComboBox.setBackground(new java.awt.Color(0, 153, 153));
        DriverNicComboBox.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        DriverNicComboBox.setForeground(new java.awt.Color(255, 255, 255));
        DriverNicComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        DriverNicComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DriverNicComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DriverNicComboBoxMouseClicked(evt);
            }
        });
        jPanel3.add(DriverNicComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 310, 30));

        saveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        saveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel3.add(saveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        TableButton.setBackground(new java.awt.Color(127, 90, 240));
        TableButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableButton.setForeground(new java.awt.Color(204, 204, 204));
        TableButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ishan\\AppData\\Local\\Temp\\icons8_data_sheet_20px_9.png")); // NOI18N
        TableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        TableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableButton.setOpaque(false);
        TableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButtonActionPerformed(evt);
            }
        });
        jPanel3.add(TableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 120, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 620));

        setSize(new java.awt.Dimension(829, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WorkingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkingButtonActionPerformed
        String id = DriverNicComboBox.getSelectedItem().toString();
        try {
            boolean isAdded = ControlDriverDetails.AtDriver(id);
            if (isAdded) {
                saveLabel.setText("Saved");
                DefaultTableModel model = (DefaultTableModel) DriverTable.getModel();
                int a = model.getRowCount();
                for (int i = 0; i < a; i++) {
                    model.removeRow(0);
                }
                List<MDriverAt> list = null;
                try {
                    list = new ControlDriverDetails().loadDriverAt();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
                }
                Object row[] = new Object[3];
                for (int i = 0; i < list.size(); i++) {
                    row[0] = list.get(i).getNo();
                    row[1] = list.get(i).getDnic();
                    row[2] = list.get(i).getDate();
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_WorkingButtonActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new EmployeeManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    private void TableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) DriverTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MDriverAt> list = null;
        try {
            list = new ControlDriverDetails().loadDriverAt();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object row[] = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getDnic();
            row[2] = list.get(i).getDate();
            model.addRow(row);
        }
    }//GEN-LAST:event_TableButtonActionPerformed

    private void DriverNicComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DriverNicComboBoxMouseClicked
         String nic = DriverNicComboBox.getSelectedItem().toString();
         
        DefaultTableModel model = (DefaultTableModel) DriverTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MDriverAt> list = null;

        try {
            list = new ControlDriverDetails().loadDriAt(nic);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DriverAttendence.class.getName()).log(Level.SEVERE, null, ex);
        }

         Object row[] = new Object[3];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getDnic();
            row[2] = list.get(i).getDate();
            model.addRow(row);
        }
    }//GEN-LAST:event_DriverNicComboBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverAttendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverAttendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton1;
    private javax.swing.JComboBox DriverNicComboBox;
    private javax.swing.JTable DriverTable;
    private javax.swing.JButton LockButton1;
    private javax.swing.JButton TableButton;
    private javax.swing.JButton WorkingButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel saveLabel;
    // End of variables declaration//GEN-END:variables

    private void Drivernic() throws ClassNotFoundException, SQLException {
        for (MDriverDetails temp : new ControlDriverDetails().getAllDrivers()) {
            DriverNicComboBox.addItem(temp.getNic());
        }
    }

}
