/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.employeemanagement;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.employeemanagement.ControlDriverDetails;
import lk.lztec.cbl.control.employeemanagement.ControlHelperDetails;
import lk.lztec.cbl.module.employeemanagement.MHelperDetails;
import lk.lztec.cbl.module.employeemanagement.MHelperSa;
import lk.lztec.cbl.view.menu.EmployeeManagement;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class HelperSalary extends javax.swing.JFrame {

    /**
     * Creates new form HelperSalary
     */
    public HelperSalary() {
        initComponents();
        try {
            Helpernic();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AmountTextField2 = new javax.swing.JTextField();
        paidButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HelperSalaryTable = new javax.swing.JTable();
        TableButton = new javax.swing.JButton();
        HelperNicComboBox = new javax.swing.JComboBox();
        DoneButton1 = new javax.swing.JButton();
        LockButton1 = new javax.swing.JButton();
        saveLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Helper Driver");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(24, 23, 54));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(36, 31, 60));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Helper_Nic");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 40));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Amount ");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        AmountTextField2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        AmountTextField2.setForeground(new java.awt.Color(204, 204, 204));
        AmountTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        AmountTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AmountTextField2.setOpaque(false);
        jPanel5.add(AmountTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 310, -1));

        paidButton.setBackground(new java.awt.Color(127, 90, 240));
        paidButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        paidButton.setForeground(new java.awt.Color(204, 204, 204));
        paidButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/low_price_20px.png"))); // NOI18N
        paidButton.setText("Paid");
        paidButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        paidButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paidButton.setOpaque(false);
        paidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidButtonActionPerformed(evt);
            }
        });
        jPanel5.add(paidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 120, 30));

        HelperSalaryTable.setBackground(new java.awt.Color(0, 153, 153));
        HelperSalaryTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        HelperSalaryTable.setForeground(new java.awt.Color(255, 255, 255));
        HelperSalaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Helper_Nic", "Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        HelperSalaryTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HelperSalaryTable.setGridColor(new java.awt.Color(255, 255, 255));
        HelperSalaryTable.setOpaque(false);
        HelperSalaryTable.setSelectionBackground(new java.awt.Color(153, 255, 204));
        HelperSalaryTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(HelperSalaryTable);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 460, 620));

        TableButton.setBackground(new java.awt.Color(127, 90, 240));
        TableButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableButton.setForeground(new java.awt.Color(204, 204, 204));
        TableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/data_sheet_20px.png"))); // NOI18N
        TableButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        TableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableButton.setOpaque(false);
        TableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButtonActionPerformed(evt);
            }
        });
        jPanel5.add(TableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 120, 50));

        HelperNicComboBox.setBackground(new java.awt.Color(0, 153, 153));
        HelperNicComboBox.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        HelperNicComboBox.setForeground(new java.awt.Color(255, 255, 255));
        HelperNicComboBox.setBorder(null);
        HelperNicComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HelperNicComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelperNicComboBoxMouseClicked(evt);
            }
        });
        jPanel5.add(HelperNicComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 300, 30));

        DoneButton1.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton1.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton1.setText("Done ");
        DoneButton1.setBorder(null);
        DoneButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(DoneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 210, 50));

        LockButton1.setBackground(new java.awt.Color(85, 91, 111));
        LockButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton1.setForeground(new java.awt.Color(204, 204, 204));
        LockButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton1.setText("LogScreen");
        LockButton1.setBorder(null);
        LockButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(LockButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        saveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        saveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel5.add(saveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 620));

        setSize(new java.awt.Dimension(897, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidButtonActionPerformed
        String id = HelperNicComboBox.getSelectedItem().toString();
        int sal = Integer.parseInt(AmountTextField2.getText());

        boolean isAdded = false;
        try {
            isAdded = ControlHelperDetails.saveHelperSa(id, sal);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (isAdded) {
            saveLabel.setText("Saved");
            DefaultTableModel model = (DefaultTableModel) HelperSalaryTable.getModel();
            int a = model.getRowCount();
            for (int i = 0; i < a; i++) {
                model.removeRow(0);
            }
            ArrayList<MHelperSa> list = null;
            try {
                list = (ArrayList<MHelperSa>) new ControlHelperDetails().loadHelperSa();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
            }
            Object row[] = new Object[4];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getNo();
                row[1] = list.get(i).getHnic();
                row[2] = list.get(i).getSal();
                row[3] = list.get(i).getDate();
                model.addRow(row);
            }
        }

    }//GEN-LAST:event_paidButtonActionPerformed

    private void TableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) HelperSalaryTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        ArrayList<MHelperSa> list = null;
        try {
            list = new ControlHelperDetails().loadHelperSa();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getHnic();
            row[2] = list.get(i).getSal();
            row[3] = list.get(i).getDate();
            model.addRow(row);
        }
    }//GEN-LAST:event_TableButtonActionPerformed

    private void DoneButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButton1ActionPerformed
        new EmployeeManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButton1ActionPerformed

    private void LockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButton1ActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButton1ActionPerformed

    private void HelperNicComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelperNicComboBoxMouseClicked
        String nic = HelperNicComboBox.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) HelperSalaryTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MHelperSa> list = null;

        try {
            list = new ControlHelperDetails().loadhelpsa(nic);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HelperSalary.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object row[] = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getHnic();
            row[2] = list.get(i).getSal();
            row[3] = list.get(i).getDate();
            model.addRow(row);
    }//GEN-LAST:event_HelperNicComboBoxMouseClicked
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelperSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelperSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelperSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelperSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelperSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountTextField2;
    private javax.swing.JButton DoneButton1;
    private javax.swing.JComboBox HelperNicComboBox;
    private javax.swing.JTable HelperSalaryTable;
    private javax.swing.JButton LockButton1;
    private javax.swing.JButton TableButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton paidButton;
    private javax.swing.JLabel saveLabel;
    // End of variables declaration//GEN-END:variables

    private void Helpernic() throws ClassNotFoundException, SQLException {
        for (MHelperDetails temp : new ControlHelperDetails().getAllHelpers()) {
            HelperNicComboBox.addItem(temp.getNic());
        }
    }
}
