/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.employeemanagement;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import lk.lztec.cbl.control.employeemanagement.ControlDriverDetails;
import lk.lztec.cbl.control.stockcontrolling.ControlProductDetails;
import lk.lztec.cbl.module.employeemanagement.MDriverDetails;
import lk.lztec.cbl.view.menu.EmployeeManagement;
import lk.lztec.cbl.view.security.LogScreen;

/**
 *
 * @author Ishan
 */
public class NewDriver extends javax.swing.JFrame {

    /**
     * Creates new form NewDriver
     */
    public NewDriver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DriverNicTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        AgeTextField = new javax.swing.JTextField();
        LockButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SaveNewProductButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        SexTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Driver");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(24, 23, 54));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Driver_Nic");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 40));

        jLabel13.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Address");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Name");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 30));

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Age");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 30));

        DriverNicTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        DriverNicTextField.setForeground(new java.awt.Color(204, 204, 204));
        DriverNicTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        DriverNicTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DriverNicTextField.setOpaque(false);
        jPanel5.add(DriverNicTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 86, 310, 30));

        AddressTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        AddressTextField.setForeground(new java.awt.Color(204, 204, 204));
        AddressTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        AddressTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AddressTextField.setOpaque(false);
        jPanel5.add(AddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 310, 30));

        NameTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        NameTextField.setForeground(new java.awt.Color(204, 204, 204));
        NameTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        NameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NameTextField.setOpaque(false);
        jPanel5.add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 156, 310, 30));

        AgeTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        AgeTextField.setForeground(new java.awt.Color(204, 204, 204));
        AgeTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        AgeTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        AgeTextField.setOpaque(false);
        jPanel5.add(AgeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 226, 310, 30));

        LockButton.setBackground(new java.awt.Color(85, 91, 111));
        LockButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton.setForeground(new java.awt.Color(204, 204, 204));
        LockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton.setText("LogScreen");
        LockButton.setBorder(null);
        LockButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButtonActionPerformed(evt);
            }
        });
        jPanel5.add(LockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        DeleteButton.setBackground(new java.awt.Color(127, 90, 240));
        DeleteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(204, 204, 204));
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/trash_20px.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        DeleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteButton.setOpaque(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel5.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 120, 30));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/save_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Save");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel5.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 120, 30));

        DoneButton.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton.setText("Done ");
        DoneButton.setBorder(null);
        DoneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        jPanel5.add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sex");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 30));

        SexTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SexTextField.setForeground(new java.awt.Color(204, 204, 204));
        SexTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        SexTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SexTextField.setOpaque(false);
        jPanel5.add(SexTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 296, 310, 30));

        PhoneTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        PhoneTextField.setForeground(new java.awt.Color(204, 204, 204));
        PhoneTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        PhoneTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PhoneTextField.setOpaque(false);
        jPanel5.add(PhoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 310, 30));

        jLabel17.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Phone");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 30));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 160, 50));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 0, 89));
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 170, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        setSize(new java.awt.Dimension(443, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButtonActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String nic = DriverNicTextField.getText();
        try {
            boolean isDeleted = ControlDriverDetails.DeleteDriver(nic);
            if (isDeleted) {
                jLabel2.setText("Deleted ");
                jLabel1.setText("");
            } else {
                jLabel2.setText("Delete fail");
                jLabel1.setText("");
            }

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String nic = DriverNicTextField.getText();
        String name = NameTextField.getText();
        int age = Integer.parseInt(AgeTextField.getText());
        String sex = SexTextField.getText();
        String address = AddressTextField.getText();
        int phone = Integer.parseInt(PhoneTextField.getText());
        MDriverDetails mDriverDetails = new MDriverDetails(nic, name, age, sex, address, phone);
        try {
            boolean isAdded = ControlDriverDetails.saveDriver(mDriverDetails);
            if (isAdded) {
                DriverNicTextField.setText("");
                NameTextField.setText("");
                AgeTextField.setText("");
                SexTextField.setText("");
                AddressTextField.setText("");
                PhoneTextField.setText("");
                jLabel1.setText("Saved");
                jLabel2.setText("");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        new EmployeeManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JTextField DriverNicTextField;
    private javax.swing.JButton LockButton;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JTextField SexTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
