/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.sales;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lk.lztec.cbl.control.sales.ControlSales;
import lk.lztec.cbl.control.stockcontrolling.ControlLorryStock;
import lk.lztec.cbl.control.stockcontrolling.ControlProductDetails;
import lk.lztec.cbl.module.sales.Mbill;
import lk.lztec.cbl.module.stockcontrolling.MLorryStock;
import lk.lztec.cbl.view.security.LogScreen;
import lk.lztec.cbl.view.menu.Sales;

/**
 *
 * @author Ishan
 */
public class NewSales extends javax.swing.JFrame {

    /**
     * Creates new form NewSales
     */
    public NewSales() {
        initComponents();
        try {
            bill();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            losto();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        QtyTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        DiscountTextField = new javax.swing.JTextField();
        SaveNewProductButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        LockButton = new javax.swing.JButton();
        BillComboBox1 = new javax.swing.JComboBox();
        LisComboBox2 = new javax.swing.JComboBox();
        saveLabel = new javax.swing.JLabel();
        SaveLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Sales");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(24, 23, 54));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(36, 31, 60));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Lorry_Stock_Id");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 40));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Bill_No");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        jLabel15.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Qty");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));

        QtyTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        QtyTextField.setForeground(new java.awt.Color(204, 204, 204));
        QtyTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        QtyTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        QtyTextField.setOpaque(false);
        jPanel5.add(QtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 310, -1));

        jLabel16.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Discount");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 30));

        DiscountTextField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        DiscountTextField.setForeground(new java.awt.Color(204, 204, 204));
        DiscountTextField.setText("0");
        DiscountTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        DiscountTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DiscountTextField.setOpaque(false);
        jPanel5.add(DiscountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 310, -1));

        SaveNewProductButton.setBackground(new java.awt.Color(127, 90, 240));
        SaveNewProductButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SaveNewProductButton.setForeground(new java.awt.Color(204, 204, 204));
        SaveNewProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/save_20px.png"))); // NOI18N
        SaveNewProductButton.setText("Save");
        SaveNewProductButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        SaveNewProductButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveNewProductButton.setOpaque(false);
        SaveNewProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveNewProductButtonActionPerformed(evt);
            }
        });
        jPanel5.add(SaveNewProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 120, 30));

        DoneButton.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton.setText("Done ");
        DoneButton.setBorder(null);
        DoneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        jPanel5.add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 220, 50));

        LockButton.setBackground(new java.awt.Color(85, 91, 111));
        LockButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton.setForeground(new java.awt.Color(204, 204, 204));
        LockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton.setText("LogScreen");
        LockButton.setBorder(null);
        LockButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButtonActionPerformed(evt);
            }
        });
        jPanel5.add(LockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 210, 50));

        BillComboBox1.setBackground(new java.awt.Color(0, 153, 153));
        BillComboBox1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        BillComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(BillComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 310, 30));

        LisComboBox2.setBackground(new java.awt.Color(0, 153, 153));
        LisComboBox2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        LisComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        LisComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LisComboBox2MouseClicked(evt);
            }
        });
        jPanel5.add(LisComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, 30));

        saveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        saveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel5.add(saveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 180, 50));

        SaveLabel.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        SaveLabel.setForeground(new java.awt.Color(0, 153, 153));
        jPanel5.add(SaveLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 170, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 620));

        setSize(new java.awt.Dimension(443, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveNewProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveNewProductButtonActionPerformed
        String lsid = LisComboBox2.getSelectedItem().toString();
        int bno = Integer.parseInt(BillComboBox1.getSelectedItem().toString());
        int qty = Integer.parseInt(QtyTextField.getText());
        int dis = Integer.parseInt(DiscountTextField.getText());
        double getAll = 0;
        try {
            getAll = ControlLorryStock.getsSprice(lsid);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (dis < 0) {
            double tot = (getAll* qty) -(dis);
            try {
                boolean isAdd = ControlSales.addsales(lsid, bno, qty, dis, tot);
                boolean isUpdate = ControlLorryStock.downqty(lsid, qty);
                boolean isUpdatep = ControlSales.addTotal(bno, tot);
                SaveLabel.setText("save");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            double tot = (getAll* qty) -(dis);
            try {
                boolean isAdd = ControlSales.addsales(lsid, bno, qty, dis, tot);
                boolean isUpdate = ControlLorryStock.downqty(lsid, qty);
                boolean isUpdatep = ControlSales.addTotal(bno, tot);
                SaveLabel.setText("save");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(NewSales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_SaveNewProductButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        new Sales().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void LockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButtonActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButtonActionPerformed

    private void LisComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LisComboBox2MouseClicked

    }//GEN-LAST:event_LisComboBox2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BillComboBox1;
    private javax.swing.JTextField DiscountTextField;
    private javax.swing.JButton DoneButton;
    private javax.swing.JComboBox LisComboBox2;
    private javax.swing.JButton LockButton;
    private javax.swing.JTextField QtyTextField;
    private javax.swing.JLabel SaveLabel;
    private javax.swing.JButton SaveNewProductButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel saveLabel;
    // End of variables declaration//GEN-END:variables

    private void losto() throws ClassNotFoundException, SQLException {
        for (MLorryStock temp : new ControlLorryStock().loadlsTable()) {
            LisComboBox2.addItem(temp.getLsid());
        }
    }

    private void bill() throws ClassNotFoundException, SQLException {
        for (Mbill temp : new ControlSales().getAllbills()) {
            BillComboBox1.addItem(temp.getBno());
        }
    }
}
