/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.lztec.cbl.view.sales;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.lztec.cbl.control.sales.ControlSales;
import lk.lztec.cbl.module.sales.MSales;
import lk.lztec.cbl.module.sales.Mbill;
import lk.lztec.cbl.view.security.LogScreen;
import lk.lztec.cbl.view.menu.Sales;

/**
 *
 * @author Ishan
 */
public class PreviousSales extends javax.swing.JFrame {

    /**
     * Creates new form PreviousSales
     */
    public PreviousSales() {
        initComponents();
        try {
            loadbill();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PreviousSales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PreviousSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AmountTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        LockButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        TableButton = new javax.swing.JButton();
        BillNoComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Previous Sales");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(24, 23, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, -1, 70));

        AmountTable.setBackground(new java.awt.Color(0, 153, 153));
        AmountTable.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        AmountTable.setForeground(new java.awt.Color(255, 255, 255));
        AmountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale No", "lorry_stock_id", "Bill No", "qty", "discount", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AmountTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AmountTable.setGridColor(new java.awt.Color(255, 255, 255));
        AmountTable.setOpaque(false);
        AmountTable.setSelectionBackground(new java.awt.Color(153, 255, 204));
        AmountTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(AmountTable);
        if (AmountTable.getColumnModel().getColumnCount() > 0) {
            AmountTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 550));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Bil_No");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, 40));

        LockButton.setBackground(new java.awt.Color(85, 91, 111));
        LockButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LockButton.setForeground(new java.awt.Color(204, 204, 204));
        LockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/lock_20px.png"))); // NOI18N
        LockButton.setText("LogScreen");
        LockButton.setBorder(null);
        LockButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButtonActionPerformed(evt);
            }
        });
        jPanel3.add(LockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 250, 70));

        DoneButton.setBackground(new java.awt.Color(85, 91, 111));
        DoneButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DoneButton.setForeground(new java.awt.Color(204, 204, 204));
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/checked_20px.png"))); // NOI18N
        DoneButton.setText("Done ");
        DoneButton.setBorder(null);
        DoneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        jPanel3.add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 240, 70));

        TableButton.setBackground(new java.awt.Color(127, 90, 240));
        TableButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TableButton.setForeground(new java.awt.Color(204, 204, 204));
        TableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/lztec/cbl/icon/data_sheet_20px.png"))); // NOI18N
        TableButton.setBorder(null);
        TableButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableButton.setOpaque(false);
        TableButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableButtonMouseClicked(evt);
            }
        });
        TableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableButtonActionPerformed(evt);
            }
        });
        jPanel3.add(TableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 60, 70));

        BillNoComboBox.setBackground(new java.awt.Color(0, 153, 153));
        BillNoComboBox.setForeground(new java.awt.Color(255, 255, 255));
        BillNoComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillNoComboBoxMouseClicked(evt);
            }
        });
        jPanel3.add(BillNoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 310, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 620));

        setSize(new java.awt.Dimension(906, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButtonActionPerformed
        new LogScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LockButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        new Sales().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void TableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableButtonActionPerformed
         DefaultTableModel model = (DefaultTableModel) AmountTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MSales> list = null;
       
        try {
            list = new ControlSales().getAllSales();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PreviousBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PreviousBill.class.getName()).log(Level.SEVERE, null, ex);
        }

            Object row[] = new Object[6];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getBno();
                row[1] = list.get(i).getLsid();
                row[2] = list.get(i).getBno();
                row[3] = list.get(i).getQty();
                row[4] = list.get(i).getDis();
                row[5] = list.get(i).getTot();
                model.addRow(row);
            }
    }//GEN-LAST:event_TableButtonActionPerformed

    private void TableButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableButtonMouseClicked

    }//GEN-LAST:event_TableButtonMouseClicked

    private void BillNoComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillNoComboBoxMouseClicked
        int bno = Integer.parseInt(BillNoComboBox.getSelectedItem().toString());
        DefaultTableModel model = (DefaultTableModel) AmountTable.getModel();
        int a = model.getRowCount();
        for (int i = 0; i < a; i++) {
            model.removeRow(0);
        }
        List<MSales> list = null;

        list = new ControlSales().loadsales(bno);

        Object row[] = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getSno();
            row[1] = list.get(i).getLsid();
            row[2] = list.get(i).getBno();
            row[3] = list.get(i).getQty();
            row[4] = list.get(i).getDis();
            row[5] = list.get(i).getTot();
            model.addRow(row);
        }
    }//GEN-LAST:event_BillNoComboBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviousSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviousSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviousSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviousSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviousSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AmountTable;
    private javax.swing.JComboBox BillNoComboBox;
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton LockButton;
    private javax.swing.JButton TableButton;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadbill() throws ClassNotFoundException, SQLException {
        for (Mbill temp : new ControlSales().getAllbills()) {
            BillNoComboBox.addItem(temp.getBno());
        }
    }
}
